CREATE TABLE Musician (

SSN VARCHAR(11) NOT NULL, 
Full_Name VARCHAR(45) NOT NULL, 
Address VARCHAR(45) NOT NULL, 
House_Number VARCHAR(12) NOT NULL UNIQUE,
PRIMARY KEY(SSN)

);

CREATE TABLE Musician_Talents (

No_Of_Songs INT NOT NULL, 
No_Of_Instruments INT NOT NULL, 
SSN VARCHAR(11) NOT NULL UNIQUE, 
PRIMARY KEY(SSN) , 

FOREIGN KEY(SSN)
 REFERENCES Musician(SSN) ON UPDATE CASCADE
 ON DELETE CASCADE
);

CREATE TABLE Instrument (

InstrumentID INT NOT NULL UNIQUE, 
Full_Name VARCHAR(45) NOT NULL,  
Musical_Key VARCHAR(10) NOT NULL, 
SSN VARCHAR(11) NOT NULL,
PRIMARY KEY(InstrumentID), 

FOREIGN KEY(SSN)
REFERENCES Musician(SSN) ON UPDATE CASCADE
ON DELETE CASCADE

);

CREATE TABLE Album (

AlbumID INT NOT NULL UNIQUE, 
Title VARCHAR(45) NOT NULL, 
Copyright_Date VARCHAR(10) NOT NULL, 
Format VARCHAR(10) NOT NULL, 
Playlist_Size INT NOT NULL,
SSN VARCHAR(11) NOT NULL ,
PRIMARY KEY (AlbumID),

FOREIGN KEY(SSN)
REFERENCES Musician(SSN) ON UPDATE CASCADE ON DELETE CASCADE


);

CREATE TABLE Song (

AlbumID INT NOT NULL, 
TrackID INT NOT NULL, 
Title VARCHAR(45) NOT NULL, 
SSN_Author VARCHAR(11) NOT NULL, 
PRIMARY KEY(AlbumID, TrackID), 

FOREIGN KEY(SSN_Author)
 REFERENCES Musician(SSN) ON UPDATE CASCADE ON DELETE CASCADE
 
);